@startuml
'https://plantuml.com/class-diagram

class Inscripcion
class Asignatura
class Alumno

Inscripcion o-- Asignatura
Inscripcion o-- Alumno

class Inscripcion {
-alumno: Alumno
-asignaturas: List<Asignatura>

+aprobada(): boolean
}

class Asignatura {
-nombre: String
-correlativasAprobadas: List<Asignatura>
-correlativasRegularizadas: List<Asignatura>
}

class Alumno {
-nombre: String
-materiasAprobadas: List<Asignatura>
-materiasRegularizadas: List<Asignatura>

+puedeCursar(in Asignatura asignatura): boolean
}
@enduml